### ISSUE TITLE
Marker Click not work

### ISSUE THREAD

**Issue by nicolae1992** [osmdroid/osmdroid#1181]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
-Open map
-Create marker
-Rotate map 30 degrees or more
-Click Marker not work

![ezgif com-resize 2](https://user-images.githubusercontent.com/4725914/47854082-dbd7a600-ddf1-11e8-8230-020e68f26595.gif)

## Environment
```
Marker mr = new Marker(map);
mr.setOnMarkerClickListener((marker, mapView) -> {
          log .......
            return true;
        });

 mr.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
```
### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2 and 6.0.1

**Comment by monsieurtanuki** [comment]
@nicolae1992 Fixed (cf. #516) for 6.0.3, but I guess it's also part of the current 6.0.2, as you can check in demo "More Samples / Data / Marker" (use the top-right menu to rotate the map). I even tried with a less square-shaped icon, and it works.
How fresh is your 6.0.2?

**Comment by nicolae1992** [comment]
compile 'org.osmdroid:osmdroid-android:6.0.2@arr'

**Comment by nicolae1992** [comment]
When will available next version?

**Comment by nicolae1992** [comment]
@monsieurtanuki in demo it's work, maybe you set ->
`Marker.setAnchor(Marker.ANCHOR_CENTER, _Marker.ANCHOR_CENTER_);`
but i set ->
`Marker.setAnchor(Marker.ANCHOR_CENTER, _Marker.ANCHOR_BOTTOM_);`

**Comment by monsieurtanuki** [comment]
@nicolae1992 In the demo it's also `Marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);` (as you can see [here](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java#L43)), and anyway the anchor is taken into account.

Can you call `Marker.isDisplayed()` in your code? If not, then you don't have the latest version.
According to @spyhunter99 in #1001 you can use the SNAPSHOT version: it will include the latest code.

**Comment by monsieurtanuki** [comment]
Fixed: it was about computing the correct orientation, and it took me only one character to fix the issue...
The code in `draw` used to be:
````java
float rotationOnScreen = (mFlat ? -mBearing : mapView.getMapOrientation()-mBearing);
````
but is now
````java
float rotationOnScreen = (mFlat ? -mBearing : -mapView.getMapOrientation()-mBearing);
````
@nicolae1992 Thanks for creating this (now fixed) issue. While the PR is merged and the snapshot created, you can create your own marker class that extends `Marker` and overrides its `draw` method, copying the whole method code with just one fix: the `float rotationOnScreen` line.

**Comment by monsieurtanuki** [comment]
@nicolae1992 Managed to try with the code edit I suggested?

**Comment by monsieurtanuki** [comment]
@nicolae1992 Now that version 6.0.3 has just been released, could you try again?

**Comment by TFreudi1** [comment]
I is still not working, I only get the ballon when I tip the marker, but the OnClick is'nt called.

**Comment by TFreudi1** [comment]
For me it is working now on 6.0.3, forget my comment from yesterday, I deleted it.

**Comment by monsieurtanuki** [comment]
@TFreudi1 Thank you!
@nicolae1992 Seems to be fixed: could you please test again with version 6.0.3 and close the issue if relevant?

**Comment by TFreudi1** [comment]
Yes it is fixed in 6.0.3, but I can't close it, because I did'nt open it :-)

**Comment by monsieurtanuki** [comment]
@nicolae1992 Assuming @TFreudi1 is talking about the very same issue you experienced, as it's fixed in 6.0.3 I close the issue. Feel free to reopen it if relevant.
