### ISSUE TITLE
Bubble not following its Marker/Polyline/Polygon when panning/zooming

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#865]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

The InfoWindow doesn't follow map movements. 
Can be seen with the Markers used in the demo app. 

### Version of osmdroid the issue relates to:
Head (6.0)

**Comment by spyhunter99** [comment]
seems ok to me, which sample?

**Comment by spyhunter99** [comment]
i see a slight drawing issue when the map is animating to a new location and the infowindow is visible. It kind of dances around where it is supposed to be

**Comment by MKergall** [comment]
I observe that on: 
Animations: Animated Marker, Marker Animations (all of them)
Data: "Military Icons using Markers", "Marker"

Using an Emulator with SDK 5.1 / API 21.

**Comment by spyhunter99** [comment]
> Animations: Animated Marker, Marker Animations (all of them)

confirmed. All the animation thing does is call `Marker#setPosition`. I found a partial fix for fixing the position of the info window when `Marker#setPosition` is called. About to push it. However, clickong on an icon, which center's the map, still has issues as well as the initial click on the marker.

**Comment by spyhunter99** [comment]
partial fix pushed, however it has a few issues. 
- On Click of the info window used to close the info window, doesn't work any more.
- sometimes, on click of the info window set's the map center to an incorrect location, not sure why. This may occur by panning the map, starting on the info window.

I also noticed that as soon the info window is shown, the mapview/gpu does into a never ending onDraw cycle.

**Comment by spyhunter99** [comment]
draw cycle is due to this branch's "fix" which in the onDraw method, calls showInfoWindow, which will remove and readd it self to the mapview's view group, which calls invalidate, which calls onDraw

**Comment by spyhunter99** [comment]
#460 related

**Comment by spyhunter99** [comment]
@MKergall i just published an updated snapshot, please retest when you can. i'm going to close this issue for now, but please reopen if its still a problem

**Comment by MKergall** [comment]
Yes, I confirm it's fixed for Markers. 
But InfoWindow can be used for other overlays (inheriting from OverlayWithIW), like Polygon and Polyline. And it's not fixed for them. 

I had a look at the fix: I understand that at each Marker.draw, you hide and show the InfoWindow again. Similar action should be done for other overlays. It will not be straightforward, because for Polyline and Polygon, the InfoWindow position to maintain depends on where the users clicked on the overlay. 

Anyway, I'm really suprised that InfoWindow do not follow map movements automatically, as it was before 6.0. If we could get this behaviour back, there would be no fix to implement everywhere. 

If no way to get this behaviour back, then a cleaner fix should be implemented, at OverlayWithIW level, to: 
- when InfoWindow is opened, store its position, 
- have a generic OverlayWithIW.draw method maintaining this position when the window is opened.

**Comment by spyhunter99** [comment]
Thanks. I'm not really sure what broke it either. It was probably the fact that we changed from "build in android scrolling" to our "custom scrolling solution which enables zoom 29".

**Comment by monsieurtanuki** [comment]
@MKergall When this issue is closed, I guess you can close #661 too.

**Comment by spyhunter99** [comment]
So lines and polygons now show the info window. It looks fine at the zoom level when the user clicked. When zooming in, the location of the marker drifts rather far away from the line/polygon. I'm not entirely sure why. Other than that, this branch is functioning for zoom, pan and rotation. Zoom animation is notably slower unfortunately. Maybe we can find another way. Instead of removing the info window from the map view's viewgroup, maybe we can just update the layout params.

**Comment by spyhunter99** [comment]
oh, and this commit changes all the constructors for line and polygon...again...

**Comment by spyhunter99** [comment]
merged. both lines and polygons uses the first point to determine the location of the bubble. This can be overridden by extending those classes.

Also, in order for the infowindow to be functional, the constructor using the map view must be used, otherwise we can't inflate the view

**Comment by spyhunter99** [comment]
reopening, there's some kind of logic issue with more than one polyline

**Comment by spyhunter99** [comment]
merged. @MKergall if you run into any more issues, please post it

**Comment by MKergall** [comment]
I just tested: it's better than before, but still not good... 

1. The bubble is not set at tap location anymore. Example: If your polyline or polygon first point is outside the view, the bubble will not be visible. Was very simple to change, I just pushed the fix (keeping your 2 lines of code in comment). 

2. You add the infoWindowLocation in each class, with a bunch of new methods. I think a simpler and more generic implementation is possible, just adding that attribute in InfoWindow. Not urgent at all.

**Comment by spyhunter99** [comment]
The issue with the change is that as you zoom in, the point that was clicked on drifts significantly. I think there's a number of possible scenarios which warrant consideration...

- center on the closest point (lines/polygons only)
- center on the point closest to the click event that is on the closest line (polygon/polyline)
- center on the average point (lines/polygons only)
- center on the marker, which makes sense for marker

**Comment by MKergall** [comment]
I don't understand the drifting you mention. 
With my change, the InfoWindow remains at its geoposition during zooms and pans: it follows the map moves - as it was before, and as it is for Markers. 
From my point of view, this is the behaviour expected by the user. 
Do you observe a drifting compared to this geoposition? Or do you expect a different behaviour?

**Comment by spyhunter99** [comment]
i'll take a video to demonstrate

**Comment by spyhunter99** [comment]
https://youtu.be/k0h9_kb_MNw

**Comment by spyhunter99** [comment]
@MKergall did you see the video? I think it has to do with calculate if the tap/click was close to a given line.

**Comment by spyhunter99** [comment]
@monsieurtanuki is there a method to go from long based point `PointL` to a geo point?

**Comment by monsieurtanuki** [comment]
@spyhunter99 I don't have my laptop now. I found `Projection.fromPixels`, with `int` instead of `long`. That will work with "decent" pixel coordinates, but not necessarily with long values. Do you have a specific need with large values? I guess a new method is needed then, with something like a "modulo world map size" in it.

**Comment by spyhunter99** [comment]
@monsieurtanuki looking at `LinearRing#isCloseTo`. Goal is to change it from returning a true/false value but to return a GeoPoint on a polyline that is closest to the input GeoPoint. From within that method, there's a PointL object that is used to walk along the line in order to find out if any of the points was close enough to the input point. I therefore need to convert the PointL object back to a GeoPoint.

**Comment by MKergall** [comment]
@spyhunter99 OK, seen the video, I understand your issue. This is an issue for Polyline, not for Polygon. 
Your "tolerance" value seems quite large - on my tests, I can't "tap" on a polyline with a point so far. 

Anyway, the relevant solution is to "snap", by computing the closest geopoint ON the polyline. I think this snapping computation can very useful in various use cases, so it could be done in a separate utility class, and only handle GeoPoints. 

Proposed API: 
GeoPoint PolylineUtility.closestPointOnLine(ArrayList<GeoPoint> line, GeoPoint point)

The same class could also host the DouglasPeucker reducer -> BTW, I'm OK to move this one from OsmBonusPack.

**Comment by spyhunter99** [comment]
@MKergall roger that. I'll see what i can do. I'm going to just copy and paste the class over, Moving it with history is a tricky process and rather painful. I'd rather avoid it in this case

**Comment by spyhunter99** [comment]
i found a "snap to" algorithm but it's not geodesic, which causes all kinds of issues past z=12. ugh. Maybe it's best to just leave it as is for the time being and revisit it at a later time.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Sorry for the slow answer, but things are going a bit too fast these days.
I guess we could develop a PointL to GeoPoint method - as the issue is closed now is that still relevant?
